# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20160419_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='days',
            new_name='day',
        ),
    ]
