# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 05:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20160419_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 4, 20, 5, 29, 58, 853562, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classes',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='courses',
            name='classes',
            field=models.ManyToManyField(related_name='classes', to='courses.Classes'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='courses.Courses'),
        ),
    ]
