# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20160420_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (0, 'Sunday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='courses.Courses'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
