# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20160420_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
